### ISSUE TITLE
del_post() error

### ISSUE THREAD

**Issue by ray3210ray3210** [PyPtt/PyPtt#156]
`ptt_bot.del_post(board='Test', aid='1ctzld4f')`
只設aid會跳出error，
好像會跟_api_get_post有衝突。
我再把index設成None也會出現error(index一定要是數字)。

只有單純設index沒設aid時才會成功

### ptt_bot.del_post(board='Test', aid='1ctzld4f'
Traceback (most recent call last):
  File "/home//PTT/delete_post.py", line 9, in <module>
    ptt_bot.del_post(board='Test', aid='1ctzld4f')
  File "/home//PTTenv/lib/python3.10/site-packages/PyPtt/PTT.py", line 1054, in del_post
    _api_del_post.del_post(self, board, aid, index)
  File "/home//PTTenv/lib/python3.10/site-packages/PyPtt/_api_del_post.py", line 61, in del_post
    post_info = api.get_post(board, aid=post_aid, index=post_index, query=True)
  File "/home//PTTenv/lib/python3.10/site-packages/PyPtt/PTT.py", line 349, in get_post
    return _api_get_post.get_post(
  File "/home//PTTenv/lib/python3.10/site-packages/PyPtt/_api_get_post.py", line 54, in get_post
    raise ValueError('wrong parameter index and aid can\'t both input')
ValueError: wrong parameter index and aid can't both input

**Comment by PttCodingMan** [comment]
Let me check.

**Comment by sheisol310** [comment]
I've finished debugging for this issue and the code works for me. I will make a PR later today.

**Comment by sheisol310** [comment]
@PttCodingMan please help check the PR for the issue: #157
